"
Create a new file: EDA with dplyr.R

Save the cominc.csv and copy paste

change the path \ with /
"

# Exploratory Data Analysis with dplyr
# Visualizations using ggplot

# Install the below libaries only once the frist time
# Load the libaries each time for a new R session 

install.packages("readr")
install.packages("ggplot2")
install.packages("dplyr")

library(readr)
library(ggplot2)
library(dplyr)

# Now read in the data and explore the dataset


comics =read.csv("Session 8/comics.csv" , stringsAsFactors=TRUE)

str(comics)

glimpse(comics)
'
######### Without stringsAsFactors=TRUE
Rows: 23,272
Columns: 11
$ name         <chr> "Spider-Man (Peter Parker)", "Captain America (Steven ...
$ id           <chr> "Secret", "Public", "Public", "Public", "No Dual", "Pu...
$ align        <chr> "Good", "Good", "Neutral", "Good", "Good", "Good", "Go...
$ eye          <chr> "Hazel Eyes", "Blue Eyes", "Blue Eyes", "Blue Eyes", "...
$ hair         <chr> "Brown Hair", "White Hair", "Black Hair", "Black Hair"...
$ gender       <chr> "Male", "Male", "Male", "Male", "Male", "Male", "Male"...
$ gsm          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
$ alive        <chr> "Living Characters", "Living Characters", "Living Char...
$ appearances  <int> 4043, 3360, 3061, 2961, 2258, 2255, 2072, 2017, 1955, ...
$ first_appear <chr> "Aug-62", "Mar-41", "Oct-74", "Mar-63", "Nov-50", "Nov...
$ publisher    <chr> "marvel", "marvel", "marvel", "marvel", "marvel", "mar...
'

'
########## With stringsAsFactor=TRUE
Rows: 23,272
Columns: 11
$ name         <fct> Spider-Man (Peter Parker), Captain America (Steven Rog...
$ id           <fct> Secret, Public, Public, Public, No Dual, Public, Publi...
$ align        <fct> Good, Good, Neutral, Good, Good, Good, Good, Good, Neu...
$ eye          <fct> Hazel Eyes, Blue Eyes, Blue Eyes, Blue Eyes, Blue Eyes...
$ hair         <fct> Brown Hair, White Hair, Black Hair, Black Hair, Blond ...
$ gender       <fct> Male, Male, Male, Male, Male, Male, Male, Male, Male, ...
$ gsm          <fct> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA...
$ alive        <fct> Living Characters, Living Characters, Living Character...
$ appearances  <int> 4043, 3360, 3061, 2961, 2258, 2255, 2072, 2017, 1955, ...
$ first_appear <fct> Aug-62, Mar-41, Oct-74, Mar-63, Nov-50, Nov-61, Nov-61...
$ publisher    <fct> marvel, marvel, marvel, marvel, marvel, marvel, marvel...
'


